apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "aether-os.fullname" . }}-config
  labels:
    {{- include "aether-os.labels" . | nindent 4 }}
data:
  NODE_ENV: {{ .Values.kernel.env.NODE_ENV | quote }}
  AETHER_FS_ROOT: {{ .Values.kernel.env.AETHER_FS_ROOT | quote }}
  AETHER_PORT: {{ .Values.kernel.port | quote }}
