{{- if or .Values.secrets.aetherSecret .Values.secrets.geminiApiKey .Values.secrets.openaiApiKey .Values.secrets.anthropicApiKey -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "aether-os.fullname" . }}-secrets
  labels:
    {{- include "aether-os.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if .Values.secrets.aetherSecret }}
  AETHER_SECRET: {{ .Values.secrets.aetherSecret | b64enc | quote }}
  {{- end }}
  {{- if .Values.secrets.geminiApiKey }}
  GEMINI_API_KEY: {{ .Values.secrets.geminiApiKey | b64enc | quote }}
  {{- end }}
  {{- if .Values.secrets.openaiApiKey }}
  OPENAI_API_KEY: {{ .Values.secrets.openaiApiKey | b64enc | quote }}
  {{- end }}
  {{- if .Values.secrets.anthropicApiKey }}
  ANTHROPIC_API_KEY: {{ .Values.secrets.anthropicApiKey | b64enc | quote }}
  {{- end }}
{{- end }}
