apiVersion: v1
kind: Service
metadata:
  name: {{ include "aether-os.fullname" . }}-kernel
  labels:
    {{- include "aether-os.kernelLabels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.kernel.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "aether-os.kernelSelectorLabels" . | nindent 4 }}
